import assert from "node:assert/strict";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

const root = resolve(import.meta.dirname, "..");
const verifier = join(root, "scripts", "verify-template-contract.mjs");
const policy = JSON.parse(await readFile(join(root, "template-contract.json"), "utf8"));
test("locked template files use LF checkout bytes", () => {
  const attributes = spawnSync("git", ["-C", root, "check-attr", "eol", "--", ".github/branch-protection-checklist.md"], { encoding: "utf8" });
  assert.equal(attributes.status, 0, attributes.stderr);
  assert.match(attributes.stdout, /\.github\/branch-protection-checklist\.md: eol: lf/);
});
async function fixture() { const directory = await mkdtemp(join(tmpdir(), "template-contract-")); const project = join(directory, "project"); await cp(root, project, { recursive: true, filter: (path) => ![".git", ".harness", "dist", "output", "node_modules"].some((name) => path.endsWith(`/${name}`) || path.endsWith(`\\${name}`)) }); return { directory, project }; }
async function provenance(project, origin = { kind: "local-archive", archiveSha256: "a".repeat(64) }) { await writeFile(join(project, "template-provenance.json"), `${JSON.stringify({ schemaVersion: 1, templateRepository: "service-lasso/service-template", templateCommit: "b".repeat(40), templateVersion: policy.templateVersion, contractDigest: policy.contractDigest, origin }, null, 2)}\n`); }
function run(project) { return spawnSync(process.execPath, [verifier, "--template-root", root, "--project-root", project], { encoding: "utf8" }); }
test("valid local archive project is admitted using actual inventory", async (t) => { const { directory, project } = await fixture(); t.after(() => rm(directory, { recursive: true, force: true })); await provenance(project); const result = run(project); assert.equal(result.status, 0, result.stderr); assert.match(result.stdout, /"verified": true/); });
test("safe identity, GitHub identity and example configuration changes are admitted", async (t) => { const { directory, project } = await fixture(); t.after(() => rm(directory, { recursive: true, force: true })); const origin = { kind: "github-derived", repository: "example/lasso-weather" }; await provenance(project, origin); const manifest = JSON.parse(await readFile(join(project, "service.json"), "utf8")); manifest.id = "weather-service"; manifest.name = "Weather Service"; manifest.meta.repository.url = "https://github.com/example/lasso-weather.git"; await writeFile(join(project, "service.json"), `${JSON.stringify(manifest, null, 2)}\n`); await writeFile(join(project, "config", "example.env"), "ECHO_MESSAGE=weather\n"); const result = run(project); assert.equal(result.status, 0, result.stderr); });
test("altered executable baseline is denied", async (t) => { const { directory, project } = await fixture(); t.after(() => rm(directory, { recursive: true, force: true })); await provenance(project); await writeFile(join(project, "runtime", "linux", "echo-service.sh"), "#!/usr/bin/env bash\necho altered\n"); const result = run(project); assert.notEqual(result.status, 0); assert.match(result.stderr, /immutable_baseline/); });
test("arbitrary artifact source change is denied", async (t) => { const { directory, project } = await fixture(); t.after(() => rm(directory, { recursive: true, force: true })); await provenance(project); const manifest = JSON.parse(await readFile(join(project, "service.json"), "utf8")); manifest.artifact.source.repo = "attacker/example"; await writeFile(join(project, "service.json"), `${JSON.stringify(manifest, null, 2)}\n`); const result = run(project); assert.notEqual(result.status, 0); assert.match(result.stderr, /forbidden_manifest_change/); });
test("secret-like configuration is denied", async (t) => { const { directory, project } = await fixture(); t.after(() => rm(directory, { recursive: true, force: true })); await provenance(project); await writeFile(join(project, "config", "example.env"), "API_TOKEN=not-allowed\n"); const result = run(project); assert.notEqual(result.status, 0); assert.match(result.stderr, /unsafe_configuration/); });
test("arbitrary configuration URL is denied", async (t) => { const { directory, project } = await fixture(); t.after(() => rm(directory, { recursive: true, force: true })); await provenance(project); await writeFile(join(project, "config", "example.env"), "UPSTREAM=https://attacker.invalid/payload\n"); const result = run(project); assert.notEqual(result.status, 0); assert.match(result.stderr, /unsafe_configuration/); });
test("malformed provenance is denied", async (t) => { const { directory, project } = await fixture(); t.after(() => rm(directory, { recursive: true, force: true })); await writeFile(join(project, "template-provenance.json"), "{bad json"); const result = run(project); assert.notEqual(result.status, 0); assert.match(result.stderr, /malformed_provenance/); });
